### PR TITLE
Regenerated locally

### PR DESCRIPTION
**Pull request by pgleeson**
@mqnifestkelvin please make sure to run https://github.com/mqnifestkelvin/modelspec/blob/main/test_all.sh before committing. There are some strange substitutions in your file e.g. Section->List. These are removed when the test script is run and everything gets regenerated.
Also check that the files listed at https://github.com/ModECI/modelspec/pull/41/files in your pull request just reflect the minimal changes you have made.

### CODE REVIEW

**Comment by mqnifestkelvin** [comment]
Good morning mentor, apologies for not merging sooner, i was figuring out the logic for the "id" to "value" replacement and also how to as efficiently as possible implementthe name spaces for modelspecs as best as possible. By the end of the day I'd push my commit to the fork for it to be merged. I will surely run the test_all.sh script and also understand why substitute are happening.

**Comment by mqnifestkelvin** [comment]
Also mentor I'm a little confused here "Also check that the files listed at https://github.com/ModECI/modelspec/pull/41/files in your pull request just reflect the minimal changes you have made." 
What do you want me to do.

**Comment by pgleeson** [comment]
@mqnifestkelvin I mean it's always good to check the pr and make sure all changes and files are what you intended to commit. For example are netid.json/xml/jaml actually required: https://github.com/ModECI/modelspec/pull/41/files#diff-91469d489de37ba9d55c005b4351d38cb65683f31394ad28924487a96b0fd708 or are these just generated files from the tests and can be ignored/not committed?

**Comment by mqnifestkelvin** [comment]
Ooh I apologize for this, I think these were reminants of the previous test I was running, I will endeavor to be more careful and will also upload a correct one after the test are all passing.

**Pull request merged**
